CGET_HAS_DEPENDENCY(zlib GITHUB madler/zlib FINDNAME ZLIB)

#CGET_HAS_DEPENDENCY(OpenSSL  GITHUB openssl/openssl)
CGET_HAS_DEPENDENCY(protobuf GITHUB jdavidberger/protobuf FINDNAME Protobuf OPTIONS "-Dprotobuf_BUILD_TESTS:bool=OFF -Dprotobuf_MSVC_STATIC_RUNTIME:BOOL=OFF")

CGET_HAS_DEPENDENCY(grpc GITHUB grpc/grpc 
			 OPTIONS "-D_gRPC_BASELIB_LIBRARIES=pthread -DgRPC_INSTALL=ON -DgRPC_SSL_PROVIDER=package -DgRPC_PROTOBUF_PROVIDER=package -DPROTOBUF_ROOT_DIR=${CGET_protobuf_REPO_DIR} -DgRPC_ZLIB_PROVIDER=package -DBORINGSSL_ROOT_DIR=${CGET_OpenSSL_REPO_DIR}" FINDNAME gRPC )
#			 NOSUBMODULES OPTIONS "-D_gRPC_BASELIB_LIBRARIES=pthread -DgRPC_INSTALL=ON  -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DZLIB_ROOT_DIR=${CGET_zlib_REPO_DIR} -DPROTOBUF_ROOT_DIR=${CGET_protobuf_REPO_DIR} -DBORINGSSL_ROOT_DIR=${CGET_OpenSSL_REPO_DIR}" FINDNAME gRPC )

set(ARGS_NO_FIND_PACKAGE "true")